import { Product } from "./types";

export const PRODUCTS: Product[] = [
  // --- SOFAS ---
  {
    id: "prod-sofa-01",
    name: "Haveli Velvet 3-Seater Sofa",
    slug: "haveli-velvet-3-seater",
    category: "sofas",
    categoryLabel: "Sofas",
    price: 68500,
    comparePrice: 79000,
    rating: 4.9,
    reviewCount: 38,
    tagline: "Lush olive micro-velvet wrapped over seasoned Burma teak frames.",
    description: "Inspired by the breezy verandahs of southern estates, the Haveli sofa merges deep feather-down blend seating with tailored fluted arms and hand-rubbed teak legs.",
    longDescription: "The Haveli 3-Seater is the centerpiece your living sanctuary deserves. Built on kiln-dried solid Burma teak with mortise-and-tenon joinery, it features multi-density reflex foam wrapped in plush channel-stitched micro-velvet. Every cushion is individually pocketed for zero motion transfer, making it equally suited for lively conversations and afternoon naps.",
    materials: ["Solid Burma Teak", "Premium Micro-Velvet", "High-Density HR Foam", "Brass Ferrules"],
    dimensions: {
      width: "220 cm",
      depth: "96 cm",
      height: "82 cm",
      seatHeight: "44 cm",
    },
    colors: [
      { name: "Olive Moss", hex: "#4A5D43" },
      { name: "Warm Terracotta", hex: "#D9673F" },
      { name: "Midnight Charcoal", hex: "#1C1C1E" },
      { name: "Oatmeal Cream", hex: "#E8E2D5" },
    ],
    primaryImage: "/images/products/haveli-velvet-1.jpg",
    hoverImage: "/images/products/haveli-velvet-2.jpg",
    galleryImages: [
      "/images/products/haveli-velvet-1.jpg",
      "/images/products/haveli-velvet-2.jpg",
      "/images/hero/hero-living.jpg",
    ],
    tags: ["Best Seller", "Signature Series", "Bespoke Millwork"],
    isBestseller: true,
    inStock: true,
    leadTime: "7-10 Days Delivery across AP & Tirupati",
  },
  {
    id: "prod-sofa-02",
    name: "Kiran Modular Corner Sectional",
    slug: "kiran-modular-corner-sectional",
    category: "sofas",
    categoryLabel: "Sofas",
    price: 94000,
    comparePrice: 112000,
    rating: 5.0,
    reviewCount: 29,
    tagline: "Endless configurations with heavy textured linen boucle.",
    description: "A low-slung, lounge-forward silhouette engineered with interlocking magnetic cleats to easily rearrange from an L-shape to an expansive daybed.",
    longDescription: "Designed for modern open-plan homes, the Kiran Sectional features three modular segments that dock together effortlessly. Upholstered in spill-resistant textured boucle with subtle flecks of warm taupe, this sofa withstands joyful family gatherings while retaining its museum-grade architectural profile.",
    materials: ["Engineered Birch Ply", "Performance Textured Boucle", "Feather-Down Layer", "Steel Cleats"],
    dimensions: {
      width: "290 cm",
      depth: "185 cm",
      height: "76 cm",
      seatHeight: "41 cm",
    },
    colors: [
      { name: "Raw Ecru", hex: "#EAE5D9" },
      { name: "Muted Sand", hex: "#D1C7B7" },
      { name: "Slate Grey", hex: "#4B4F56" },
    ],
    primaryImage: "/images/products/kiran-l-shape-1.jpg",
    hoverImage: "/images/products/kiran-l-shape-2.jpg",
    galleryImages: [
      "/images/products/kiran-l-shape-1.jpg",
      "/images/products/kiran-l-shape-2.jpg",
      "/images/rooms/living-room.jpg",
    ],
    tags: ["Modular", "Trending", "New"],
    isNew: true,
    inStock: true,
    leadTime: "12-14 Days Custom Made",
  },
  {
    id: "prod-sofa-03",
    name: "Nila Curved Bouclé Loveseat",
    slug: "nila-curved-boucle-loveseat",
    category: "sofas",
    categoryLabel: "Sofas",
    price: 49500,
    comparePrice: 56000,
    rating: 4.8,
    reviewCount: 42,
    tagline: "Organic sculpture meets cloud-like cozy comfort.",
    description: "Curving gracefully like a flowing river stone, the Nila brings visual softness to angular spaces with tactile Italian curled bouclé.",
    longDescription: "The Nila Loveseat breaks the monotony of straight lines. Its continuous organic backrest provides wrap-around lumbar support, creating a cozy nook for reading or intimate chats. Finished with concealed recessed glides that give it a floating appearance off the floor.",
    materials: ["Steam-bent Beechwood", "Italian Curly Bouclé", "Dual-density Memory Foam"],
    dimensions: {
      width: "168 cm",
      depth: "88 cm",
      height: "75 cm",
      seatHeight: "42 cm",
    },
    colors: [
      { name: "Butter Cream", hex: "#F2D98B" },
      { name: "Terracotta Rose", hex: "#C76D58" },
      { name: "Pure Ivory", hex: "#F5F3ED" },
    ],
    primaryImage: "/images/products/nila-loveseat-1.jpg",
    hoverImage: "/images/products/nila-loveseat-2.jpg",
    galleryImages: [
      "/images/products/nila-loveseat-1.jpg",
      "/images/products/nila-loveseat-2.jpg",
    ],
    tags: ["Compact Living", "Statement Piece"],
    inStock: true,
    leadTime: "5-7 Days Dispatch",
  },
  {
    id: "prod-sofa-04",
    name: "Raga Cognac Leather Lounge Armchair",
    slug: "raga-leather-lounge-armchair",
    category: "chairs",
    categoryLabel: "Chairs",
    price: 36500,
    comparePrice: 42000,
    rating: 4.9,
    reviewCount: 51,
    tagline: "Top-grain drum-dyed leather that patinas richly over decades.",
    description: "An homage to mid-century Scandinavian armchairs reinterpreted with thick bridle leather straps and brass hardware.",
    longDescription: "Crafted in our Srikalahasthi woodworking workshop, the Raga Armchair pairs hand-buffed saddle leather with an oil-finished teak wood chassis. The sloping seat angle supports proper spinal alignment, making it your favorite chair from day one and looking even better with age.",
    materials: ["Burma Teak", "Full-Grain Waxed Saddle Leather", "Antique Brass Rivets"],
    dimensions: {
      width: "78 cm",
      depth: "84 cm",
      height: "80 cm",
      seatHeight: "39 cm",
    },
    colors: [
      { name: "Cognac Amber", hex: "#A85D2A" },
      { name: "Espresso Black", hex: "#221D1A" },
      { name: "Saddle Tan", hex: "#C2854E" },
    ],
    primaryImage: "/images/products/raga-recliner-1.jpg",
    hoverImage: "/images/products/raga-recliner-2.jpg",
    galleryImages: [
      "/images/products/raga-recliner-1.jpg",
      "/images/products/raga-recliner-2.jpg",
      "/images/hero/about-craft.jpg",
    ],
    tags: ["Full-Grain Leather", "Handmade"],
    isBestseller: true,
    inStock: true,
    leadTime: "In Stock - 3 Days",
  },

  // --- BEDS ---
  {
    id: "prod-bed-01",
    name: "Aranya Low-Profile Oak Platform Bed",
    slug: "aranya-platform-bed",
    category: "beds",
    categoryLabel: "Beds",
    price: 72000,
    comparePrice: 84000,
    rating: 4.9,
    reviewCount: 31,
    tagline: "Solid white oak platform with integrated floating night ledges.",
    description: "Minimalist Japanese joinery meets Indian timber durability. The extended platform creates seamless bedside perches without visual clutter.",
    longDescription: "The Aranya Platform Bed elevates your bedroom into a tranquil retreat. Built without visible screws using traditional bridle joints, the massive headboard displays expressive bookmatched wood grain finished with zero-VOC organic hardwax oils.",
    materials: ["Solid White Oak", "LVL Solid Slats", "Zero-VOC Hardwax Oil"],
    dimensions: {
      width: "210 cm",
      depth: "225 cm",
      height: "88 cm",
    },
    colors: [
      { name: "Natural Blonde Oak", hex: "#D6C4A5" },
      { name: "Smoked Walnut", hex: "#483A2E" },
      { name: "Ebonized Ash", hex: "#262320" },
    ],
    primaryImage: "/images/products/aranya-bed-1.jpg",
    hoverImage: "/images/products/aranya-bed-2.jpg",
    galleryImages: [
      "/images/products/aranya-bed-1.jpg",
      "/images/products/aranya-bed-2.jpg",
      "/images/rooms/bedroom.jpg",
    ],
    tags: ["Minimalist", "Solid Wood", "Platform"],
    isBestseller: true,
    inStock: true,
    leadTime: "10-14 Days Custom Build",
  },
  {
    id: "prod-bed-02",
    name: "Veda Fluted Linen King Bed",
    slug: "veda-fluted-linen-king-bed",
    category: "beds",
    categoryLabel: "Beds",
    price: 81000,
    comparePrice: 95000,
    rating: 4.8,
    reviewCount: 24,
    tagline: "Architectural vertical fluting wrapped in Belgian oatmeal linen.",
    description: "An imposing 140cm tall upholstered headboard with sound-dampening acoustic backing that brings 5-star hotel luxury home.",
    longDescription: "Each flute of the Veda Bed is individually hand-pleated and padded with memory foam for a tactile, luxurious backrest while reading in bed. The perimeter frame features soft radius corners to prevent any toe-stubbing in the dark.",
    materials: ["Belgian Heavy Linen", "Acoustic Core Padding", "Kiln-dried Hardwood Frame"],
    dimensions: {
      width: "198 cm",
      depth: "218 cm",
      height: "140 cm",
    },
    colors: [
      { name: "Oatmeal Cream", hex: "#E7DFD3" },
      { name: "Warm Greige", hex: "#B3A799" },
      { name: "Sage Mist", hex: "#8E9E88" },
    ],
    primaryImage: "/images/products/veda-king-1.jpg",
    hoverImage: "/images/products/veda-king-2.jpg",
    galleryImages: [
      "/images/products/veda-king-1.jpg",
      "/images/products/veda-king-2.jpg",
    ],
    tags: ["Luxury", "Acoustic Backing"],
    isNew: true,
    inStock: true,
    leadTime: "10-12 Days",
  },
  {
    id: "prod-bed-03",
    name: "Lotus Hydraulic Storage King Bed",
    slug: "lotus-hydraulic-storage-bed",
    category: "beds",
    categoryLabel: "Beds",
    price: 88500,
    comparePrice: 104000,
    rating: 4.9,
    reviewCount: 47,
    tagline: "Effortless German gas-lift mechanism with 950L concealed storage.",
    description: "Maximize your apartment square footage without sacrificing an ounce of elegance. Sealed dust-free underbed storage chamber.",
    longDescription: "The Lotus Bed solves urban bedroom storage with heavy-duty gas pistons rated for 50,000 cycles. The lift deck operates with a single finger touch, revealing a carpet-lined trunk that swallows suitcases, duvets, and seasonal wardrobe effortlessly.",
    materials: ["Marine Grade Birch Ply", "German Gas Struts", "Teak Veneer Exterior", "Linen Headboard"],
    dimensions: {
      width: "192 cm",
      depth: "215 cm",
      height: "105 cm",
    },
    colors: [
      { name: "Warm Teak & Cream", hex: "#8F5E36" },
      { name: "Dark Walnut & Grey", hex: "#3B2E24" },
    ],
    primaryImage: "/images/products/lotus-bed-1.jpg",
    hoverImage: "/images/products/lotus-bed-2.jpg",
    galleryImages: [
      "/images/products/lotus-bed-1.jpg",
      "/images/products/lotus-bed-2.jpg",
    ],
    tags: ["Hydraulic Storage", "Space Saver"],
    inStock: true,
    leadTime: "7-10 Days",
  },
  {
    id: "prod-bed-04",
    name: "Nimbus Cane & Teak Daybed",
    slug: "nimbus-cane-teak-daybed",
    category: "beds",
    categoryLabel: "Beds",
    price: 43000,
    comparePrice: 49500,
    rating: 4.7,
    reviewCount: 19,
    tagline: "Hand-woven natural rattan side panels on sculptured teak legs.",
    description: "Versatile daybed that transitions between a living room divider, reading bench, and comfortable guest sleeper.",
    longDescription: "Woven by second-generation craft artisans in Andhra Pradesh, the octagonal rattan cane panels allow air circulation while casting poetic shadow patterns when sunlight filters through. Topped with a tailored linen tufted mattress bolster.",
    materials: ["Solid CP Teak", "Natural Hand-woven Rattan", "Raw Cotton Mattress"],
    dimensions: {
      width: "205 cm",
      depth: "90 cm",
      height: "68 cm",
      seatHeight: "42 cm",
    },
    colors: [
      { name: "Natural Honey Teak", hex: "#BA7C48" },
      { name: "Antique Walnut", hex: "#4A3525" },
    ],
    primaryImage: "/images/products/nimbus-daybed-1.jpg",
    hoverImage: "/images/products/nimbus-daybed-2.jpg",
    galleryImages: [
      "/images/products/nimbus-daybed-1.jpg",
      "/images/products/nimbus-daybed-2.jpg",
    ],
    tags: ["Handmade Cane", "Verandah Style"],
    inStock: true,
    leadTime: "5-7 Days",
  },

  // --- DINING ---
  {
    id: "prod-dining-01",
    name: "Chakra Fluted Pedestal Round Dining Table",
    slug: "chakra-fluted-pedestal-table",
    category: "dining",
    categoryLabel: "Dining",
    price: 64000,
    comparePrice: 75000,
    rating: 5.0,
    reviewCount: 33,
    tagline: "Solid wood tambour pedestal that sparks circular conversations.",
    description: "Seats 6 with generous legroom thanks to the central fluted pillar base. Finished with a satin water-repellent seal that laughs off turmeric stains.",
    longDescription: "The Chakra Round Dining Table is made for shared meals and lingering talks. Its 135cm diameter solid acacia tabletop features a chamfered bullnose edge that rests comfortably against forearms. The base contains an internal steel stabilizer that prevents any rocking.",
    materials: ["Solid Acacia & Teak", "Steel Weighted Core", "Stain-proof Ceramic Nano Seal"],
    dimensions: {
      width: "135 cm",
      depth: "135 cm",
      height: "76 cm",
    },
    colors: [
      { name: "Golden Honey Acacia", hex: "#B88349" },
      { name: "Charcoal Ash", hex: "#292725" },
    ],
    primaryImage: "/images/products/chakra-dining-1.jpg",
    hoverImage: "/images/products/chakra-dining-2.jpg",
    galleryImages: [
      "/images/products/chakra-dining-1.jpg",
      "/images/products/chakra-dining-2.jpg",
      "/images/rooms/dining.jpg",
    ],
    tags: ["Best Seller", "Stain-Proof"],
    isBestseller: true,
    inStock: true,
    leadTime: "Ready to Ship",
  },
  {
    id: "prod-dining-02",
    name: "Mati Live Edge Acacia Dining Table + Bench",
    slug: "mati-live-edge-dining-table",
    category: "dining",
    categoryLabel: "Dining",
    price: 78500,
    comparePrice: 92000,
    rating: 4.9,
    reviewCount: 26,
    tagline: "Natural tree contours with brass butterfly joint inlays.",
    description: "Every table is a one-of-a-kind natural sculpture preserving the organic edge of centuries-old sustainably salvaged timber.",
    longDescription: "The Mati Table celebrates the raw narrative of wood. Knots and natural drying fissures are stabilized with solid cast brass butterfly keys (dovetails). Paired with matching live edge bench and matte black trapezoid steel trestles.",
    materials: ["Salvaged Solid Acacia Slab", "Cast Brass Keys", "Matte Powdercoated Steel"],
    dimensions: {
      width: "210 cm",
      depth: "98 cm",
      height: "76 cm",
    },
    colors: [
      { name: "Raw Bark Acacia", hex: "#7E5233" },
      { name: "Warm Teak Stain", hex: "#9E6436" },
    ],
    primaryImage: "/images/products/mati-bench-1.jpg",
    hoverImage: "/images/products/mati-bench-2.jpg",
    galleryImages: [
      "/images/products/mati-bench-1.jpg",
      "/images/products/mati-bench-2.jpg",
    ],
    tags: ["One of a Kind", "Live Edge"],
    inStock: true,
    leadTime: "12-14 Days Custom Slab Selection",
  },
  {
    id: "prod-dining-03",
    name: "Indigo Minimalist Extendable Dining Table",
    slug: "indigo-extendable-table",
    category: "dining",
    categoryLabel: "Dining",
    price: 58000,
    comparePrice: 68000,
    rating: 4.8,
    reviewCount: 37,
    tagline: "Expands from 6 seats (160cm) to 10 seats (240cm) in 15 seconds.",
    description: "Concealed butterfly leaf mechanism slides smoothly on German ball-bearing runners. Razor-thin beveled edge with solid core strength.",
    longDescription: "Hosting a festival dinner or Sunday brunch? The Indigo's hidden extension leaf pops up effortlessly without requiring an extra person. Made with high-pressure matte laminate top over solid birch ply for scratch and heat resistance up to 180°C.",
    materials: ["Anti-scratch FENIX Core", "Solid Oak Legs", "Steel Extension Synchronizer"],
    dimensions: {
      width: "160 - 240 cm",
      depth: "90 cm",
      height: "75 cm",
    },
    colors: [
      { name: "Matte Chalk White", hex: "#F0EFEA" },
      { name: "Cast Iron Grey", hex: "#32302F" },
    ],
    primaryImage: "/images/products/indigo-table-1.jpg",
    hoverImage: "/images/products/indigo-table-2.jpg",
    galleryImages: [
      "/images/products/indigo-table-1.jpg",
      "/images/products/indigo-table-2.jpg",
    ],
    tags: ["Extendable", "Urban Home"],
    inStock: true,
    leadTime: "7 Days Delivery",
  },
  {
    id: "prod-dining-04",
    name: "Terra Cast Terrazzo Counter Bar Table",
    slug: "terra-terrazzo-bar-table",
    category: "dining",
    categoryLabel: "Dining",
    price: 42000,
    comparePrice: 49000,
    rating: 4.7,
    reviewCount: 15,
    tagline: "Speckled river aggregate and brass accents for morning espresso bars.",
    description: "Sturdy counter-height dining piece ideal for open kitchen breakfast nooks and evening cocktail hours.",
    longDescription: "Hand-poured using Andhra river pebbles, quartz chips, and terracotta aggregate. Polished to a buttery smooth semi-matte luster that feels cool to the touch and resists red wine, citrus, and coffee oils.",
    materials: ["Engineered Terrazzo Slab", "Brushed Brass Foot Rail", "Solid Ash Frame"],
    dimensions: {
      width: "140 cm",
      depth: "60 cm",
      height: "92 cm",
    },
    colors: [
      { name: "Terracotta Speckle", hex: "#D48265" },
      { name: "Verde Olive Chip", hex: "#8F9983" },
    ],
    primaryImage: "/images/products/terra-bar-1.jpg",
    hoverImage: "/images/products/terra-bar-2.jpg",
    galleryImages: [
      "/images/products/terra-bar-1.jpg",
      "/images/products/terra-bar-2.jpg",
    ],
    tags: ["Terrazzo", "Kitchen Counter"],
    inStock: true,
    leadTime: "6-8 Days",
  },

  // --- CHAIRS ---
  {
    id: "prod-chair-01",
    name: "Surya Terracotta Velvet Accent Chair",
    slug: "surya-accent-chair",
    category: "chairs",
    categoryLabel: "Chairs",
    price: 24500,
    comparePrice: 29000,
    rating: 4.9,
    reviewCount: 64,
    tagline: "Sun-drenched warmth in rich brick velvet and sculpted wooden elbows.",
    description: "The ideal reading companion. Sculpted paddle armrests offer the perfect resting spot for your book or chai cup.",
    longDescription: "The Surya Accent Chair has become an instant icon in modern Indian homes. Upholstered in our signature heavyweight terracotta velvet with high rub counts, it combines an ergonomic 105-degree lumbar recline with turned solid wood stiles.",
    materials: ["Solid Sheesham Wood", "Durasoft Velvet", "Pocket Spring Seat Core"],
    dimensions: {
      width: "74 cm",
      depth: "82 cm",
      height: "78 cm",
      seatHeight: "43 cm",
    },
    colors: [
      { name: "Brick Terracotta", hex: "#D9673F" },
      { name: "Sage Grass", hex: "#7E8E76" },
      { name: "Turmeric Gold", hex: "#E8B83D" },
    ],
    primaryImage: "/images/products/surya-chair-1.jpg",
    hoverImage: "/images/products/surya-chair-2.jpg",
    galleryImages: [
      "/images/products/surya-chair-1.jpg",
      "/images/products/surya-chair-2.jpg",
    ],
    tags: ["Best Seller", "Velvet Accent"],
    isBestseller: true,
    inStock: true,
    leadTime: "In Stock - Dispatch in 24h",
  },
  {
    id: "prod-chair-02",
    name: "Dew Leather Executive Swivel Chair",
    slug: "dew-swivel-office-chair",
    category: "chairs",
    categoryLabel: "Chairs",
    price: 31000,
    comparePrice: 36000,
    rating: 4.9,
    reviewCount: 45,
    tagline: "360° pneumatic tilt swivel disguised as a designer club chair.",
    description: "Say goodbye to sterile plastic office chairs. Warm saddle leather and bent walnut shell bring warmth to your home studio.",
    longDescription: "The Dew Swivel balances executive work performance with boutique residential warmth. Includes synchronized knee-tilt lock, pneumatic height lift, and quiet soft-polyurethane castors safe for hardwood and stone floors.",
    materials: ["Molded Walnut Ply", "Top-Grain Supple Leather", "Polished Aluminum Mechanism"],
    dimensions: {
      width: "66 cm",
      depth: "68 cm",
      height: "85 - 94 cm",
      seatHeight: "45 - 54 cm",
    },
    colors: [
      { name: "Caramel Brown", hex: "#A36B3B" },
      { name: "Raven Black", hex: "#1F1D1C" },
    ],
    primaryImage: "/images/products/dew-swivel-1.jpg",
    hoverImage: "/images/products/dew-swivel-2.jpg",
    galleryImages: [
      "/images/products/dew-swivel-1.jpg",
      "/images/products/dew-swivel-2.jpg",
      "/images/rooms/workspace.jpg",
    ],
    tags: ["Home Office", "Ergonomic"],
    isNew: true,
    inStock: true,
    leadTime: "3-5 Days",
  },
  {
    id: "prod-chair-03",
    name: "Bliss Architectural Rocking Chair",
    slug: "bliss-rocking-chair",
    category: "chairs",
    categoryLabel: "Chairs",
    price: 28000,
    comparePrice: 33000,
    rating: 4.8,
    reviewCount: 28,
    tagline: "Continuous bentwood runners calibrated for soothing, whisper-quiet motion.",
    description: "A rhythmic masterpiece. The sweeping ashwood runners are damp-padded with felt underneath to protect marble and tiles.",
    longDescription: "Whether nursing a newborn or unwinding with evening jazz, the Bliss Rocker delivers harmonic tranquility. Built using 16 layers of laminated ash, steam-pressed into an unbroken continuous curve that holds up to 180kg with effortless poise.",
    materials: ["Steam-bent White Ash", "Belgian Raw Linen Cushion", "Wool Felt Dampers"],
    dimensions: {
      width: "70 cm",
      depth: "96 cm",
      height: "84 cm",
      seatHeight: "44 cm",
    },
    colors: [
      { name: "Bleached Ash & Cream", hex: "#DFD7CA" },
      { name: "Walnut & Charcoal", hex: "#43352B" },
    ],
    primaryImage: "/images/products/bliss-rocker-1.jpg",
    hoverImage: "/images/products/bliss-rocker-2.jpg",
    galleryImages: [
      "/images/products/bliss-rocker-1.jpg",
      "/images/products/bliss-rocker-2.jpg",
    ],
    tags: ["Rocking Chair", "Nursery & Lounge"],
    inStock: true,
    leadTime: "5-7 Days",
  },
  {
    id: "prod-chair-04",
    name: "Yuga Bouclé Barrel Tub Chair",
    slug: "yuga-barrel-tub-chair",
    category: "chairs",
    categoryLabel: "Chairs",
    price: 21500,
    comparePrice: 25000,
    rating: 4.7,
    reviewCount: 39,
    tagline: "Curved 360-degree cocoon wrapped in heavy nubby bouclé.",
    description: "Compact footprint that fits snug in corners, bedroom vanity alcoves, or flanking a credenza.",
    longDescription: "The Yuga Tub Chair is a favorite among our interior designers for small apartments. Its rounded back hugs the shoulders comfortably while the compact 72cm diameter doesn't crowd tight walkways.",
    materials: ["Curved Plywood Shell", "Thick Loop Bouclé", "Internal Swivel Plate"],
    dimensions: {
      width: "72 cm",
      depth: "74 cm",
      height: "72 cm",
      seatHeight: "41 cm",
    },
    colors: [
      { name: "Chalk Bouclé", hex: "#F3EFE6" },
      { name: "Warm Camel", hex: "#BA8C57" },
    ],
    primaryImage: "/images/products/yuga-barrel-1.jpg",
    hoverImage: "/images/products/yuga-barrel-2.jpg",
    galleryImages: [
      "/images/products/yuga-barrel-1.jpg",
      "/images/products/yuga-barrel-2.jpg",
    ],
    tags: ["Swivel Tub", "Space Saver"],
    inStock: true,
    leadTime: "In Stock",
  },

  // --- STORAGE ---
  {
    id: "prod-storage-01",
    name: "Atlas Open Grid Teak Bookshelf",
    slug: "atlas-open-grid-bookshelf",
    category: "storage",
    categoryLabel: "Storage",
    price: 52000,
    comparePrice: 62000,
    rating: 5.0,
    reviewCount: 34,
    tagline: "Asymmetric architectural shelving that doubles as an airy room partition.",
    description: "Display your favorite art, ceramics, and books. Staggered compartment heights accommodate tall coffee-table editions and sprawling trailing plants.",
    longDescription: "Crafted from seasoned plantation teak with hand-mortised partitions, the Atlas Bookshelf is finished cleanly on all 360 degrees, allowing it to stand proudly against a wall or float mid-room as a space divider between dining and lounge.",
    materials: ["Solid Plantation Teak", "Matte Polyurethane Protective Seal", "Concealed Wall Anchors"],
    dimensions: {
      width: "160 cm",
      depth: "36 cm",
      height: "195 cm",
    },
    colors: [
      { name: "Natural Warm Teak", hex: "#A56D3B" },
      { name: "Smoked Espresso", hex: "#352A20" },
    ],
    primaryImage: "/images/products/atlas-bookshelf-1.jpg",
    hoverImage: "/images/products/atlas-bookshelf-2.jpg",
    galleryImages: [
      "/images/products/atlas-bookshelf-1.jpg",
      "/images/products/atlas-bookshelf-2.jpg",
    ],
    tags: ["Room Divider", "Handcrafted Teak"],
    isBestseller: true,
    inStock: true,
    leadTime: "7-10 Days",
  },
  {
    id: "prod-storage-02",
    name: "Koshi Low-Profile Media Credenza",
    slug: "koshi-low-profile-credenza",
    category: "storage",
    categoryLabel: "Storage",
    price: 46000,
    comparePrice: 54000,
    rating: 4.9,
    reviewCount: 48,
    tagline: "Tambour slatted doors that slide around curves seamlessly.",
    description: "Slatted acoustic doors allow remote IR signals and speaker sound to pass through while keeping cables and gaming consoles neatly tucked away.",
    longDescription: "The Koshi Credenza was engineered for modern entertainment. Featuring internal cable routing chases, ventilated rear heat exhausts for amplifiers, and curved tambour wood slats that slide like butter into recessed side tracks.",
    materials: ["Solid Oak Tambour Slats", "MDF Oak Veneer Core", "Soft-close Drawers"],
    dimensions: {
      width: "190 cm",
      depth: "45 cm",
      height: "52 cm",
    },
    colors: [
      { name: "Nordic White Oak", hex: "#C7B299" },
      { name: "Dark Walnut", hex: "#4A392B" },
    ],
    primaryImage: "/images/products/koshi-credenza-1.jpg",
    hoverImage: "/images/products/koshi-credenza-2.jpg",
    galleryImages: [
      "/images/products/koshi-credenza-1.jpg",
      "/images/products/koshi-credenza-2.jpg",
    ],
    tags: ["Media Console", "Tambour Slats"],
    inStock: true,
    leadTime: "Ready to Ship",
  },
  {
    id: "prod-storage-03",
    name: "Hira Natural Rattan 3-Door Wardrobe",
    slug: "hira-rattan-3-door-wardrobe",
    category: "storage",
    categoryLabel: "Storage",
    price: 89000,
    comparePrice: 105000,
    rating: 4.9,
    reviewCount: 22,
    tagline: "Airy woven cane fronts that keep clothes fresh in humid climates.",
    description: "Full interior customization: double hanging rails, cedar-lined jewelry trays, and pull-out shoe galleries.",
    longDescription: "The Hira Wardrobe combines the heirloom beauty of vintage armoires with precision modern cabinetry. Natural rattan wicker panels allow delicate fabrics like silks and linens to breathe naturally, preventing mustiness in coastal Andhra weather.",
    materials: ["Solid CP Teak Frame", "Imported Grade-A Wicker Rattan", "Brass Bar Pulls"],
    dimensions: {
      width: "180 cm",
      depth: "62 cm",
      height: "210 cm",
    },
    colors: [
      { name: "Golden Honey Cane", hex: "#B37E44" },
      { name: "Vintage Bleached", hex: "#DFD1B7" },
    ],
    primaryImage: "/images/products/hira-wardrobe-1.jpg",
    hoverImage: "/images/products/hira-wardrobe-2.jpg",
    galleryImages: [
      "/images/products/hira-wardrobe-1.jpg",
      "/images/products/hira-wardrobe-2.jpg",
    ],
    tags: ["Custom Storage", "Breathable Cane"],
    isNew: true,
    inStock: true,
    leadTime: "14 Days Custom Build",
  },
  {
    id: "prod-storage-04",
    name: "Prism Brass & Travertine Side Table Pair",
    slug: "prism-brass-travertine-side-tables",
    category: "storage",
    categoryLabel: "Storage",
    price: 26000,
    comparePrice: 31000,
    rating: 4.8,
    reviewCount: 31,
    tagline: "Honed Roman travertine slab floating over brushed champagne brass legs.",
    description: "Sold as an overlapping nesting pair. Perfect for flexible seating arrangements and bedside luxury.",
    longDescription: "Every travertine top displays porous geological pits and creamy butter-colored mineral strata. Honed smooth and treated with an invisible oleophobic sealant so condensation rings wipe away without a mark.",
    materials: ["Natural Roman Travertine Stone", "Solid Brass Rod Frame", "Felt Base Pads"],
    dimensions: {
      width: "Large: 50 cm | Small: 42 cm",
      depth: "Large: 50 cm | Small: 42 cm",
      height: "Large: 52 cm | Small: 44 cm",
    },
    colors: [
      { name: "Warm Travertine & Brass", hex: "#D6C7AC" },
      { name: "Nero Marquina & Bronze", hex: "#2B2A29" },
    ],
    primaryImage: "/images/products/prism-tables-1.jpg",
    hoverImage: "/images/products/prism-tables-2.jpg",
    galleryImages: [
      "/images/products/prism-tables-1.jpg",
      "/images/products/prism-tables-2.jpg",
    ],
    tags: ["Natural Stone", "Nesting Pair"],
    inStock: true,
    leadTime: "In Stock",
  },

  // --- LIGHTING ---
  {
    id: "prod-lighting-01",
    name: "Agni Hand-thrown Terracotta Pendant",
    slug: "agni-terracotta-pendant",
    category: "lighting",
    categoryLabel: "Lighting",
    price: 11500,
    comparePrice: 14000,
    rating: 5.0,
    reviewCount: 71,
    tagline: "Wheel-thrown earthenware clay shade that casts intimate downward warmth.",
    description: "Sculpted by local ceramic potters near Srikalahasthi, combining traditional clay methods with spun brass canopy fittings.",
    longDescription: "The Agni Pendant turns light into an intimate experience. The raw matte unglazed terracotta exterior contrasts with a glossy white interior reflector that amplifies 2700K warm LED glow over dining tables or kitchen islands.",
    materials: ["Hand-thrown Terracotta Clay", "Solid Brass Hardware", "Braided Cotton Cable"],
    dimensions: {
      width: "32 cm",
      depth: "32 cm",
      height: "26 cm",
    },
    colors: [
      { name: "Earthy Terracotta", hex: "#C4623C" },
      { name: "Charcoal Clay", hex: "#3A3633" },
      { name: "Chalk Ochre", hex: "#D9C194" },
    ],
    primaryImage: "/images/products/agni-pendant-1.jpg",
    hoverImage: "/images/products/agni-pendant-2.jpg",
    galleryImages: [
      "/images/products/agni-pendant-1.jpg",
      "/images/products/agni-pendant-2.jpg",
    ],
    tags: ["Handmade Ceramics", "Local Artisan"],
    isBestseller: true,
    inStock: true,
    leadTime: "In Stock - Dispatch in 24h",
  },
  {
    id: "prod-lighting-02",
    name: "Soma Spun Brass Arc Floor Lamp",
    slug: "soma-brass-arc-floor-lamp",
    category: "lighting",
    categoryLabel: "Lighting",
    price: 29500,
    comparePrice: 35000,
    rating: 4.8,
    reviewCount: 36,
    tagline: "Dramatic 210cm sweeping brass arc anchored by heavy Indian green marble.",
    description: "Cantilevered overhead lighting without drilling your ceiling. Foot-tap brass dimmer for effortless mood shifts.",
    longDescription: "The Soma Arc Lamp extends 165cm outward, positioning warm glare-free light squarely over your sofa coffee table. Anchored by a 22kg polished Udaipur green marble block that guarantees unwavering stability.",
    materials: ["Solid Spun Brass Shade", "Seamless Curved Brass Tube", "Udaipur Green Marble"],
    dimensions: {
      width: "165 cm reach",
      depth: "42 cm base",
      height: "210 cm",
    },
    colors: [
      { name: "Brushed Satin Brass", hex: "#D4AF37" },
      { name: "Matte Anodized Black", hex: "#222120" },
    ],
    primaryImage: "/images/products/soma-lamp-1.jpg",
    hoverImage: "/images/products/soma-lamp-2.jpg",
    galleryImages: [
      "/images/products/soma-lamp-1.jpg",
      "/images/products/soma-lamp-2.jpg",
    ],
    tags: ["Statement Floor Lamp", "Dimmable"],
    inStock: true,
    leadTime: "3-5 Days",
  },
  {
    id: "prod-lighting-03",
    name: "Luna Frosted Orb Glass Chandelier",
    slug: "luna-frosted-orb-chandelier",
    category: "lighting",
    categoryLabel: "Lighting",
    price: 38000,
    comparePrice: 45000,
    rating: 4.9,
    reviewCount: 27,
    tagline: "A cluster of 7 mouth-blown opal glass globes floating in poetic balance.",
    description: "Soft, shadowless illumination that looks like a constellation of mini moons above your dining table or stairwell.",
    longDescription: "Each glass sphere of the Luna is individually mouth-blown using three layers of glass to eliminate any hot spots or glare. Connected by articulating brass stems that can be rotated to customize your fixture's geometry.",
    materials: ["Mouth-blown Triple Opal Glass", "Architectural Brass Stems", "Integrated CRI 95 LEDs"],
    dimensions: {
      width: "95 cm",
      depth: "75 cm",
      height: "65 - 150 cm adjustable",
    },
    colors: [
      { name: "Frosted Opal & Brass", hex: "#E8E2D5" },
      { name: "Frosted Opal & Matte Black", hex: "#302E2D" },
    ],
    primaryImage: "/images/products/luna-cluster-1.jpg",
    hoverImage: "/images/products/luna-cluster-2.jpg",
    galleryImages: [
      "/images/products/luna-cluster-1.jpg",
      "/images/products/luna-cluster-2.jpg",
    ],
    tags: ["Chandelier", "Mouth-Blown Glass"],
    isNew: true,
    inStock: true,
    leadTime: "5-7 Days",
  },
  {
    id: "prod-lighting-04",
    name: "Diya Glazed Terracotta Table Lamp",
    slug: "diya-terracotta-table-lamp",
    category: "lighting",
    categoryLabel: "Lighting",
    price: 8900,
    comparePrice: 11000,
    rating: 4.9,
    reviewCount: 58,
    tagline: "Ribbed tactile earthenware with tailored Belgian raw linen drum shade.",
    description: "The bedside glow that makes winding down at night a true sensory ritual. Built-in USB-C fast charging port concealed in base.",
    longDescription: "The Diya Table Lamp infuses ancient ceramic techniques with modern convenience. The weighted ribbed terracotta base features a tactile crackle glaze, while the discreet 20W USB-C port in the rear charges your phone without nightstand cable tangles.",
    materials: ["Ribbed Earthenware with Crackle Glaze", "Raw Linen Drum Shade", "Brass Rotary Switch"],
    dimensions: {
      width: "36 cm",
      depth: "36 cm",
      height: "54 cm",
    },
    colors: [
      { name: "Warm Terracotta Glaze", hex: "#C76D58" },
      { name: "Stone White", hex: "#ECE6DC" },
      { name: "Moss Lichen", hex: "#7E8873" },
    ],
    primaryImage: "/images/products/diya-lamp-1.jpg",
    hoverImage: "/images/products/diya-lamp-2.jpg",
    galleryImages: [
      "/images/products/diya-lamp-1.jpg",
      "/images/products/diya-lamp-2.jpg",
    ],
    tags: ["Bedside Essential", "USB-C Charging"],
    isBestseller: true,
    inStock: true,
    leadTime: "In Stock - Ships Tomorrow",
  },
];
