import { PortfolioProject } from "./types";

export const PROJECTS: PortfolioProject[] = [
  {
    id: "proj-01",
    slug: "swarnamukhi-villa",
    title: "The Swarnamukhi River Villa",
    tagline: "4,200 sq.ft contemporary sanctuary blending teakwood joinery with tropical courtyards.",
    location: "Srikalahasthi, Andhra Pradesh",
    roomType: "Full Architecture & Interior Millwork",
    year: "2025",
    area: "4,200 sq.ft",
    duration: "4.5 Months",
    budgetRange: "₹38 Lakhs - ₹45 Lakhs",
    description: "Commissioned by a multi-generational family overlooking the sacred Swarnamukhi river basin. Our interior team oversaw everything from structural space replanning and custom teak ceiling rafters to bespoke dining tables, low-profile bed suites, and acoustic wall cladding.",
    coverImage: "/images/portfolio/project-1-main.jpg",
    beforeImage: "/images/portfolio/project-1-before.jpg",
    afterImage: "/images/portfolio/project-1-after.jpg",
    gallery: [
      "/images/portfolio/project-1-main.jpg",
      "/images/portfolio/project-1-after.jpg",
      "/images/rooms/living-room.jpg",
      "/images/rooms/dining.jpg",
    ],
    stats: [
      { label: "Total Area", value: "4,200 sq.ft" },
      { label: "Bespoke Pieces", value: "28 Units" },
      { label: "Handcrafted Teak", value: "100% Burma Grade" },
      { label: "Timeline", value: "On Schedule (18 Wks)" },
    ],
    clientTestimonial: {
      quote: "GYP SIGNATURES transformed our cold bare concrete structure into a breathing, deeply emotional home. Their in-house wood workshop in Srikalahasthi delivered tolerances and finishes superior to any metropolitan studio.",
      author: "Dr. K. S. Reddy & Family",
      role: "Homeowners, Srikalahasthi",
    },
    featuredProducts: ["prod-sofa-01", "prod-dining-01", "prod-storage-01"],
  },
  {
    id: "proj-02",
    slug: "tirupati-foothills-penthouse",
    title: "Tirupati Foothills Penthouse",
    tagline: "Expansive 3,400 sq.ft sky residence featuring Italian marble, fluted walnut & brass accents.",
    location: "Alipiri Road, Tirupati",
    roomType: "Penthouse Interior & Custom Wood Works",
    year: "2025",
    area: "3,400 sq.ft",
    duration: "3.5 Months",
    budgetRange: "₹28 Lakhs - ₹35 Lakhs",
    description: "Framing panoramic vistas of the holy Tirumala hills, this penthouse demanded a serene aesthetic free of visual noise. We engineered hidden flush-to-wall jib doors, curved plaster ceilings, and suspended glass lighting clusters that glow gently at dusk.",
    coverImage: "/images/portfolio/project-2-main.jpg",
    beforeImage: "/images/portfolio/project-2-before.jpg",
    afterImage: "/images/portfolio/project-2-after.jpg",
    gallery: [
      "/images/portfolio/project-2-main.jpg",
      "/images/portfolio/project-2-after.jpg",
      "/images/rooms/bedroom.jpg",
      "/images/hero/hero-living.jpg",
    ],
    stats: [
      { label: "Living Volume", value: "3,400 sq.ft" },
      { label: "Ceiling Height", value: "11.5 ft" },
      { label: "Custom Millwork", value: "14 Rooms" },
      { label: "Lighting Scenes", value: "6 Smart Zones" },
    ],
    clientTestimonial: {
      quote: "The attention to invisible detail is astonishing. The hidden storage in the master bed, the way the tambour credenza opens without a sound — GYP represents the absolute pinnacle of craft in our region.",
      author: "Venkatesh & Supriya V.",
      role: "Tech Entrepreneur & Architect",
    },
    featuredProducts: ["prod-sofa-02", "prod-bed-01", "prod-lighting-03"],
  },
  {
    id: "proj-03",
    slug: "heritage-courtyard-revival",
    title: "Heritage Courtyard House Revival",
    tagline: "Restoring an ancestral 1940s manor with modern modular luxury and climate-responsive cane.",
    location: "Bazaar Street, Srikalahasthi",
    roomType: "Restoration & Modern Furniture",
    year: "2024",
    area: "2,800 sq.ft",
    duration: "4 Months",
    budgetRange: "₹22 Lakhs - ₹28 Lakhs",
    description: "Balancing heritage respect with modern Gen Z livability. We salvaged antique brass pillars and married them with contemporary terracotta-washed accent seating, terrazzo breakfast bars, and high-performance humidity-resistant cabinetry.",
    coverImage: "/images/portfolio/project-3-main.jpg",
    beforeImage: "/images/portfolio/project-1-before.jpg",
    afterImage: "/images/portfolio/project-3-main.jpg",
    gallery: [
      "/images/portfolio/project-3-main.jpg",
      "/images/rooms/outdoor.jpg",
      "/images/hero/about-craft.jpg",
    ],
    stats: [
      { label: "Heritage Age", value: "85 Years" },
      { label: "Salvaged Wood", value: "3.2 Tonnes Reclaimed" },
      { label: "New Custom Units", value: "19 Units" },
      { label: "Energy Efficiency", value: "+40% Passive Air" },
    ],
    clientTestimonial: {
      quote: "They didn't tear down our family memories; they elevated them. Every person who steps through the brass threshold is mesmerized by the warmth.",
      author: "R. Murali Krishna",
      role: "Heritage Estate Custodian",
    },
    featuredProducts: ["prod-sofa-04", "prod-bed-04", "prod-dining-04"],
  },
  {
    id: "proj-04",
    slug: "rayalaseema-executive-duplex",
    title: "Rayalaseema Executive Duplex",
    tagline: "Acoustic fluted timber wall paneling, floating credenzas and custom media lounge.",
    location: "Chandragiri Bypass, Tirupati District",
    roomType: "Duplex Interior & Entertainment Suite",
    year: "2025",
    area: "3,100 sq.ft",
    duration: "3 Months",
    budgetRange: "₹25 Lakhs - ₹30 Lakhs",
    description: "Designed for a young surgeon couple who wanted a home tuned for high-fidelity music listening and restorative weekend calm. We implemented custom CNC-milled walnut acoustic diffusion panels, hidden subwoofer cabinets, and deep boucle lounges.",
    coverImage: "/images/portfolio/project-4-main.jpg",
    beforeImage: "/images/portfolio/project-2-before.jpg",
    afterImage: "/images/portfolio/project-4-main.jpg",
    gallery: [
      "/images/portfolio/project-4-main.jpg",
      "/images/rooms/workspace.jpg",
      "/images/products/koshi-credenza-1.jpg",
    ],
    stats: [
      { label: "Acoustic Wall Area", value: "650 sq.ft" },
      { label: "Sound Dampening", value: "NRC 0.85 Certified" },
      { label: "Bespoke Seating", value: "11-Seater Theater" },
      { label: "Completion", value: "Ahead of Schedule" },
    ],
    clientTestimonial: {
      quote: "After 14-hour hospital shifts, coming home to this acoustic sanctuary is therapeutic. The woodwork quality feels German, but the warmth is proudly Indian.",
      author: "Dr. Ananya & Dr. Gautham",
      role: "Physicians, Tirupati",
    },
    featuredProducts: ["prod-storage-02", "prod-sofa-02", "prod-lighting-02"],
  },
  {
    id: "proj-05",
    slug: "sri-krishna-modular-kitchen",
    title: "Sri Krishna Fluted Quartz Modular Kitchen",
    tagline: "German Blum soft-close hardware, anti-fingerprint FENIX laminates & fluted island.",
    location: "Padmavathi Puram, Tirupati",
    roomType: "Modular Kitchen & Pantry Design",
    year: "2025",
    area: "480 sq.ft",
    duration: "4 Weeks",
    budgetRange: "₹9 Lakhs - ₹14 Lakhs",
    description: "An ultra-sleek, ergonomic modular kitchen crafted to withstand rigorous heavy Indian cooking while looking like an architectural pavilion. Includes a 3.2m island with integrated induction, downdraft exhaust, and warm under-counter brass glow.",
    coverImage: "/images/portfolio/project-5-main.jpg",
    beforeImage: "/images/portfolio/project-1-before.jpg",
    afterImage: "/images/portfolio/project-5-main.jpg",
    gallery: [
      "/images/portfolio/project-5-main.jpg",
      "/images/rooms/dining.jpg",
    ],
    stats: [
      { label: "Island Length", value: "3.2 Meters" },
      { label: "Hardware Guarantee", value: "25-Year Blum Warranty" },
      { label: "Drawers & Carousels", value: "32 Soft-Close Units" },
      { label: "Surface Durability", value: "Anti-Scratch Heatproof" },
    ],
    clientTestimonial: {
      quote: "Turmeric, oil splashes, pressure cookers — this kitchen takes everything and wipes clean in one swipe. It's transformed how our family cooks and lives.",
      author: "Padma & S. Ramanathan",
      role: "Homeowners",
    },
    featuredProducts: ["prod-dining-04", "prod-lighting-01"],
  },
  {
    id: "proj-06",
    slug: "prakasam-modular-loft",
    title: "Prakasam Studio Loft",
    tagline: "Smart space-saving modular millwork for a Gen Z creative director.",
    location: "Srikalahasthi Industrial Growth Center",
    roomType: "Studio Loft & Workstation",
    year: "2025",
    area: "1,200 sq.ft",
    duration: "5 Weeks",
    budgetRange: "₹8 Lakhs - ₹12 Lakhs",
    description: "A compact loft that punches three times above its weight. Features a hydraulic fold-away wall bed with integrated home theater projector, floating cantilevered walnut desk, and concealed wardrobe walls.",
    coverImage: "/images/portfolio/project-6-main.jpg",
    beforeImage: "/images/portfolio/project-2-before.jpg",
    afterImage: "/images/portfolio/project-6-main.jpg",
    gallery: [
      "/images/portfolio/project-6-main.jpg",
      "/images/rooms/workspace.jpg",
      "/images/products/dew-swivel-1.jpg",
    ],
    stats: [
      { label: "Effective Area", value: "+45% Usable Space" },
      { label: "Transformer Units", value: "4 Multi-Function" },
      { label: "Integrated Power", value: "Wireless Desk Chases" },
      { label: "Build Turnaround", value: "30 Days" },
    ],
    clientTestimonial: {
      quote: "As a creative who works remotely, I needed high design without clutter. GYP gave me a studio that looks like it belongs in Milan or Brooklyn.",
      author: "Kiran Bharadwaj",
      role: "Design Lead",
    },
    featuredProducts: ["prod-chair-02", "prod-bed-03", "prod-lighting-04"],
  },
];
