import { RoomCategory } from "./types";

export const ROOMS: RoomCategory[] = [
  {
    id: "room-living",
    name: "Living Sanctuaries",
    slug: "living-room",
    tagline: "Where conversations linger and weary days melt.",
    description: "Deep-seated modular sectionals, sculptural accent seating, live edge cocktail tables, and layered ambient lighting.",
    itemCount: 14,
    image: "/images/rooms/living-room.jpg",
    gridSpan: "col-span-12 md:col-span-8 md:row-span-2",
  },
  {
    id: "room-bedroom",
    name: "Rest & Slumber",
    slug: "bedroom",
    tagline: "Minimalist platforms and fluted linen headboards.",
    description: "Low-profile solid oak beds, hydraulic storage, fluted linen headboards, and bedside stone tables.",
    itemCount: 11,
    image: "/images/rooms/bedroom.jpg",
    gridSpan: "col-span-12 md:col-span-4 md:row-span-2",
  },
  {
    id: "room-dining",
    name: "Dining & Feasts",
    slug: "dining",
    tagline: "Pedestal round tables and live-edge slabs.",
    description: "Solid acacia dining suites, extendable butterfly tables, terrazzo bars, and sculptural dining chairs.",
    itemCount: 9,
    image: "/images/rooms/dining.jpg",
    gridSpan: "col-span-12 md:col-span-4 md:row-span-1",
  },
  {
    id: "room-workspace",
    name: "Creative Studios",
    slug: "workspace",
    tagline: "Ergonomic leather swivels and cable-free walnut desks.",
    description: "Designed for deep focus. Solid timber executive desks, acoustic baffles, and ergonomic swivels.",
    itemCount: 8,
    image: "/images/rooms/workspace.jpg",
    gridSpan: "col-span-12 md:col-span-4 md:row-span-1",
  },
  {
    id: "room-kids",
    name: "Playful Quarters",
    slug: "kids",
    tagline: "Rounded corners, non-toxic finishes, modular play.",
    description: "Bespoke bunk beds, low book ledges, and resilient storage built with organic zero-VOC paints.",
    itemCount: 6,
    image: "/images/rooms/kids.jpg",
    gridSpan: "col-span-12 md:col-span-4 md:row-span-1",
  },
  {
    id: "room-outdoor",
    name: "Verandah & Courtyard",
    slug: "outdoor",
    tagline: "Weather-resistant teak lounges and stone planters.",
    description: "Seasoned Burma teak patio sectionals, cane daybeds, and monolithic granite coffee blocks.",
    itemCount: 7,
    image: "/images/rooms/outdoor.jpg",
    gridSpan: "col-span-12 md:col-span-12 md:row-span-1",
  },
];
